---
services:
  who1:
    image: traefik/whoami
    hostname: who1
    container_name: who1
    networks:
      - proxy
      - whonet
  who2:
    image: traefik/whoami
    hostname: who2
    container_name: who2
    networks:
      - proxy
      - whonet
  who3:
    image: traefik/whoami
    hostname: who3
    container_name: who3
    networks:
      - proxy
      - whonet

networks:
  whonet:
    external: false

  proxy:
    external: true
