---
services:
  who1:
    image: traefik/whoami
    hostname: who1
    container_name: who1
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true
      - traefik.http.routers.who1.rule=PathPrefix(`/who1`)
      - traefik.http.middlewares.stripwho1.stripprefix.prefixes=/who1
      - traefik.http.routers.who1.middlewares=stripwho1

  who2:
    image: traefik/whoami
    hostname: who2
    container_name: who2
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true
      - traefik.http.routers.who2.rule=Host(`who2.stage`)

  who3:
    image: traefik/whoami
    hostname: who3
    container_name: who3
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true
      - traefik.http.routers.who3.rule=(Host(`who3.stage`) && PathPrefix(`/who3`))
      - traefik.http.middlewares.stripwho3.stripprefix.prefixes=/who3
      - traefik.http.routers.who3.middlewares=stripwho3

networks:
  whonet:
    external: false

  proxy:
    external: true
