---
services:
  who1:
    image: traefik/whoami
    hostname: who1
    container_name: who1
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true
      - traefik.http.routers.who1.rule=PathPrefix(`/who1`)
      - traefik.http.middlewares.stripwho1.stripprefix.prefixes=/who1
      - traefik.http.routers.who1.middlewares=stripwho1

  who2:
    image: traefik/whoami
    hostname: who2
    container_name: who2
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true

  who3:
    image: traefik/whoami
    hostname: who3
    container_name: who3
    networks:
      - proxy
      - whonet
    labels:
      - traefik.enable=true

networks:
  whonet:
    external: false

  proxy:
    external: true
