---
services:
  proxy:
    image: traefik:v2.9
    container_name: proxy
    ports:
      - 88:80
      - 8080:8080
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /run/docker.sock:/run/docker.sock
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true
